Spring REST Docs 의존성 추가
CodeSoom/spring-week8-assignment-1 pull request #46
Opened 2022-05-10 11:51 UTC by shineoov

**Spring REST Docs** 추가했습니다.

**Spring REST Docs** 은
Spring MVC Test, WebTestClient 등 테스트에서 생성된 스니펫을 사용하여
RESTful 서비스에 대한 정확하고 읽기 쉬운 문서를 생성해 줍니다.

기본적으로 `Asciidoctor` 를 사용하고
`Asciidoctor` 텍스트를 처리하고 필요에 맞게 스타일이 지정되고 배치된 HTML 을 생성합니다.
`Markdown` 을 사용할 수도 있습니다.

[LINK](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/)

2022-05-10 12:24 UTC, johngrib requested changes
두 커밋을 주제에 맞게 분리해서 알맞게 작업하셨습니다. 잘 하셨어요!
그런데 커밋 메시지가 좀 아쉽습니다. 

1. `docs: 상품 리스트 문서` 를 의도하신 것 같은데 `dcos: 상품 리스트 문서`로 오타를 내셨습니다.
2. `docs: 상품 리스트 문서`보다 완성된 문장이면 좋을 것 같습니다. `상품 리스트 API 문서 추가`처럼 좀 더 서술형으로 작성하는 것도 방법이겠죠.

![image](https://user-images.githubusercontent.com/1855714/167627175-5d010bd9-ed55-4cc9-b54c-65e82891c16d.png)

2022-05-11 07:38 UTC, shineoov commented
> 두 커밋을 주제에 맞게 분리해서 알맞게 작업하셨습니다. 잘 하셨어요! 그런데 커밋 메시지가 좀 아쉽습니다.
> 
> 1. `docs: 상품 리스트 문서` 를 의도하신 것 같은데 `dcos: 상품 리스트 문서`로 오타를 내셨습니다.
> 2. `docs: 상품 리스트 문서`보다 완성된 문장이면 좋을 것 같습니다. `상품 리스트 API 문서 추가`처럼 좀 더 서술형으로 작성하는 것도 방법이겠죠.
> 
> ![image](https://user-images.githubusercontent.com/1855714/167627175-5d010bd9-ed55-4cc9-b54c-65e82891c16d.png)

앗 오타는 정말 안내려고 하는데 오타가 있었네요 ㅠㅠ
커밋 메시지 수정해서 force push 했습니다. ( [다른분 PR 참고](https://github.com/CodeSoom/spring-week8-assignment-1/pull/45#discussion_r869167304) )

2022-05-11 12:11 UTC, johngrib reviewed
오른쪽 위의 돌아가는 화살표 모양의 아이콘을 클릭하면 저에게 리뷰를 다시 해달라고 요청하는 것입니다.

머지해드리려다가... 이거 해보시는 게 좋을 거 같아서 하지 않았습니다. 꼭 클릭해 보세요.

![image](https://user-images.githubusercontent.com/1855714/167846563-282f8f44-bd64-413c-939f-7b7ab685466c.png)

2022-05-11 12:19 UTC, shineoov commented
> 오른쪽 위의 돌아가는 화살표 모양의 아이콘을 클릭하면 저에게 리뷰를 다시 해달라고 요청하는 것입니다.
> 
> 머지해드리려다가... 이거 해보시는 게 좋을 거 같아서 하지 않았습니다. 꼭 클릭해 보세요.
> 
> ![image](https://user-images.githubusercontent.com/1855714/167846563-282f8f44-bd64-413c-939f-7b7ab685466c.png)

오 넵 감사합니다~!

2022-05-11 12:19 UTC, closed without merging